main:
  - name: WORLD PIECE
    url: 'https://apx.wp.computer'
    weight: 2
  - name: THE UNIVERSAL PIECE
    url: 'https://apx.up.computer'
    weight: 1
  - name: WORLD PIECE COMPUTER
    url: 'https://a.wp.computer'
    weight: 3
  - name: THI
    url: 'https://thehumanimperative.up.computer'
    weight: 4
  - name: THE HUMAN IMPERATIVE
    url: 'https://timemachineforpeace.up.computer'
    weight: 5
